### ISSUE TITLE
Undefined name d

### ISSUE THREAD

**Issue by Mech7** [dericofilho/sublime-phpfmt#100]
I get an error when i try to run the command format now:

```
>>> d
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'd' is not defined
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/Users/cdekok/Library/Application Support/Sublime Text 3/Packages/phpfmt/phpfmt.py", line 1162, in run
    src = dofmt(self, self.view, None, src)
  File "/Users/cdekok/Library/Application Support/Sublime Text 3/Packages/phpfmt/phpfmt.py", line 128, in dofmt
    dirnm, sfn = os.path.split(uri)
  File "./posixpath.py", line 106, in split
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by dericofilho** [comment]
@Mech7 I am really sorry for this bug. I shall fix it ASAP.

**Comment by Mech7** [comment]
@dericofilho Don't be sorry :+1: thanks for having a look at it.

**Comment by dericofilho** [comment]
@Mech7 Were you formatting an unsaved file?

**Comment by Mech7** [comment]
@dericofilho Yes the file was not saved yet is it a requirement?

**Comment by dericofilho** [comment]
Since latest release it shouldn't be. I will double check what happened.

**Comment by dericofilho** [comment]
@Mech7 please, update to https://github.com/dericofilho/sublime-phpfmt/commit/5c4fff2d2b416aa1e4177d8092c32215723f9df3 

I should like to have your feedback before closing this issue.

**Comment by dericofilho** [comment]
@Mech7 if I don't hear from you until March 12th I shall close this issue.

**Comment by Mech7** [comment]
Hi I updated it and it seems to work fine now thanks for the fix :+1:
