### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by zoic21** [dericofilho/sublime-phpfmt#164]
Hi

I get this error since couple of day (it's work perfectly before) when I want for format my php code : 

````
phpfmt (php_ver) cmd:
 ['C:/Users/Loic/CloudStation/Sublime Text 3/php/php.exe', '-v']
phpfmt (php_ver) out:
 PHP 5.6.5 (cli) (built: Jan 21 2015 16:27:34) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies

phpfmt (php_ver) err:
 
Traceback (most recent call last):
  File "C:\Users\Loic\CloudStation\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "C:\Users\Loic\CloudStation\Sublime Text 3\Data\Packages\phpfmt\phpfmt.py", line 939, in run
    src = dofmt(self, self.view, None, src, True)
  File "C:\Users\Loic\CloudStation\Sublime Text 3\Data\Packages\phpfmt\phpfmt.py", line 375, in dofmt
    p.stdin.write(src.encode('utf-8'))
BrokenPipeError: [Errno 32] Broken pipe
````

How can I solve this ?

Thank in advance

**Comment by zoic21** [comment]
After reinstall it's ok

**Comment by dericofilho** [comment]
@zoic21 few weeks ago there was a release in which the fmt.phar self updated was buggy. That's where this bug came from. As you realized,  it is solved by reinstalling the plugin.
